### ISSUE TITLE
"Not found" error

### ISSUE THREAD

**Issue by dbil** [GCalToolkit/Sheets2GCal#39]
Most of my events have stopped being recognized when exporting.
Some events can be recognized, updated or deleted, so my first row should be fine. But I get the "Not found" error for most events. 
I can't see any difference in the rows that are recognized vs not found. Any idea ?
![Uploading Screenshot 2024-01-23 at 11.01.32 AM.png…]()

**Comment by GCalToolkit** [comment]
Could you upload the screenshot again? It's not being displayed. Did you import "All Events" or a date range, and have you edited the events in Google Calendar since they were imported/created in the Sheet?

**Comment by dbil** [comment]
![Screenshot 2024-01-23 at 11 01 32 AM](https://github.com/GCalToolkit/Sheets2GCal/assets/35175396/337b7e3b-9f54-4c59-8dde-72ea4f0e8a6e)

**Comment by GCalToolkit** [comment]
Thanks. I would start by looking at the row for this event on 1 Feb 2024 and click the "Link". If that doesn't open the event (as I suspect) then the Event ID is wrong or missing, in which case you should first check that there is actually data in the "Event ID" column. That column might be hidden, in which case you'll have to click the small black arrows to "unhide" it.

Assuming there is an event ID for that row, we need to figure out why it has changed since the event was imported/created as that is the only possible cause of this error.

Did you import "All Events" or a date range, and have you edited the events in Google Calendar since they were imported/created in the Sheet?

**Comment by dbil** [comment]
Got it thanks!!!
There is an Event ID for all events Not Found, but the events are created on the calendar from Zapier, and in the following automation step, a corresponding line is added to the gsheet. 
I found that in Zapier, in the Event ID field, a couple random letters were added before the input, messing up the Event ID on the sheet. 
Thanks for you help!

**Comment by GCalToolkit** [comment]
Interesting - did you find a solution for that in case others run into the same problem?

**Comment by GCalToolkit** [comment]
Got it! Thank you for sharing that and let me know if you run into any other issues.
