### ISSUE TITLE
How can I update an event without deleting the others

### ISSUE THREAD

**Issue by olimpiathermasparque** [GCalToolkit/Sheets2GCal#5]
Hi,
I imported calendar to sheet and it worked fine.
Now I change an event and select the relative check box in column B to Update (thats the only one true),
but when I click to update calendar from sheet, it deletes all events in that calendar and leaves only the selected event.
If I select all events to update in the column B, it only updates one event randomly.
How can I update an event without deleting the others?
Kind Regards,
André

**Comment by GCalToolkit** [comment]
Hi, that's very strange... when you edit an event the "update" column checkbox should automatically become checked, and when you go to "Update Calendar from Sheet" and click "Update" only the edited event(s) should be updated and then go green. Can you check that you don't have any other scripts associated with this SpreadSheet (Tools > Script Editor), or does this happen even in a brand new SpreadSheet?

Also, you wrote "when I click to update calendar from sheet, it deletes all events in that calendar and leaves only the selected event". Do you mean that it deletes all the other rows in the sheet, leaving just that row?

Can you also please confirm that you are not using the "Legacy" version, but have installed from https://workspace.google.com/marketplace/app/sheets2gcal/137564231775?

**Comment by olimpiathermasparque** [comment]
> Hi, that's very strange... when you edit an event the "update" column checkbox should automatically become checked, and when you go to "Update Calendar from Sheet" and click "Update" only the edited event(s) should be updated and then go green. Can you check that you don't have any other scripts associated with this SpreadSheet (Tools > Script Editor), or does this happen even in a brand new SpreadSheet?
> 
> Also, you wrote "when I click to update calendar from sheet, it deletes all events in that calendar and leaves only the selected event". Do you mean that it deletes all the other rows in the sheet, leaving just that row?
> 
> Can you also please confirm that you are not using the "Legacy" version, but have installed from https://workspace.google.com/marketplace/app/sheets2gcal/137564231775?

**Comment by olimpiathermasparque** [comment]
> Hi, that's very strange... when you edit an event the "update" column checkbox should automatically become checked, and when you go to "Update Calendar from Sheet" and click "Update" only the edited event(s) should be updated and then go green. Can you check that you don't have any other scripts associated with this SpreadSheet (Tools > Script Editor), or does this happen even in a brand new SpreadSheet?
> 
> Also, you wrote "when I click to update calendar from sheet, it deletes all events in that calendar and leaves only the selected event". Do you mean that it deletes all the other rows in the sheet, leaving just that row?
> 
> Can you also please confirm that you are not using the "Legacy" version, but have installed from https://workspace.google.com/marketplace/app/sheets2gcal/137564231775?

Yes, when I update a collumn the checkbox get checked. If I go to "Update Calendar from Sheet" and click "Update" all events are deleted from calendar and in the sheet it goes green.
I´m trying on a brand new sheet, doesn´t have any script in the editor.
In the collums C to G I can paste values from other spreadsheet? I did this instead of typping.

I installed from the Google Marketplace, how can I test if its with "Legacy" version?
Kind Regard,
André

**Comment by GCalToolkit** [comment]
The most worrying part there is "all events are deleted from calendar " - are you really saying that everything in your Google Calendar was deleted?! If so, have you moved the columns around at all? You can move all of them except the Delete and Update columns which must be A and B respectively. Yes, you can copy/paste data in from other Sheets or use formulas without any trouble.

The legacy version is at https://workspace.google.com/marketplace/app/sheets2gcal/137564231775, so you should see "Installed" on that page.

If you can share a copy of the calendar (with any sensitive information removed) with gcaltoolkit@gmail.com that would help - otherwise you can email me a copy or screenshots showing how the columns are set up.

**Comment by olimpiathermasparque** [comment]
Hi,
Yes, everything from calendar linked to the sheet.
No, no columns was moved.
If I click at https://workspace.google.com/marketplace/app/sheets2gcal/137564231775, it shows only the button "Unistall".
I will try with another sheet to see if its working.

**Comment by olimpiathermasparque** [comment]
![image](https://user-images.githubusercontent.com/83674918/117313294-240d2e80-ae5c-11eb-9944-066ed19abab2.png)
with the new sheet, it worked for the events that I typed, but not with the event I used formulas to get details from other sheet.
I got the error from image.
I tried to update the event typing the text and It worked for the line that have formulas. It seems its not working if I use formulas in the columns C,D,E,M&N

**Comment by GCalToolkit** [comment]
Sorry, yes it should say "Uninstall" so that's the right version.

It's not deleting anything from Google Calendar in the screenshot - was that only happening in your original sheet?

As for formulas causing problems, the most likely explanation is that the dates are somehow incorrect - are you using Day/Month/Year or Month/Day/Year as I can't tell from the screenshot? If you click on an imported date and a formula date do they both bring up a date picker at the correct date?

**Comment by olimpiathermasparque** [comment]
I think the problem was with the dates realy, with this new sheet it worked fine.
