### ISSUE TITLE
"Error: No Permission to edit"

### ISSUE THREAD

**Issue by Jfrancis347** [GCalToolkit/Sheets2GCal#7]
Hey team, I'm having issues updating the calendar with new information from my Google sheet. In this instance I have initially created 6 new events all of which were created successfully. I then added in guest emails (3 emails separated by comma) and 1 of the 6 events updated successfully. I tried again and 1 more event updated successfully. After this none of the events are updating and for these events I am getting the error message "Error: No Permission to edit: 'Name of event: date'". 

Also noting as I write this that the date in the error message is one day ahead of my actual event i.e. The start date is Feb 04 but the date named in the error is Jan 05 - not sure if this is related.

Thanks all

**Comment by GCalToolkit** [comment]
Hi, assuming that you aren't switching between multiple Google accounts on the same browser (which can cause similar errors) this is most likely caused by Google's restrictions on inviting guests; if you continue to create events without any guests are they created correctly?

Unfortunately Google imposes various undocumented limits for free Google accounts, as you can see on the forums here:

https://support.google.com/calendar/search?q=Problem+guests

To combat the increase of calendar spam, the number of guests you can add is now limited per event, and per minute/hour/day... and for "security reasons" these limits have not been disclosed. To test if this is the case you could try adding the same number of guests to events manually in Google Calendar, but it's also possible that API calls are restricted differently to manual input.

Paid Google Workspace accounts should not suffer from this problem after at least $60 had been billed, and if you are using such an account I recommend that you contact Google support directly to check that your quota has been raised accordingly:

https://support.google.com/a/answer/1047213

If you are using a free account, and if this is indeed the problem, then sadly there's not much any of us can do except wait a while and try again.

**Comment by Jfrancis347** [comment]
Thanks for the quick reply and for the links!

I am using a paid GSuite account, but it might well have been something to do with the calls through the API or possibly an intermittent issue. 

The good news is I have given it about an hour since trying and tried again, and everything has updated/published without issue. This includes a number of newly created events and successfully inviting guests from the existing events.

Thanks again.
